
JERRY_REACH_CHEESE   = +100
JERRY_HIT_CHEESE     = +40
JERRY_CAUGHT_BY_TOM  = -100
JERRY_NORMAL_MOVE    = -2
JERRY_DRAW           = -120

TOM_CATCH_JERRY           = +100
TOM_JERRY_REACHED_CHEESE  = -100
TOM_NORMAL_MOVE           = -1.5
TOM_DRAW                  = -120

STAY_STILL_PENALTY = -50.0
